Feat: Todo App
mhenriette/todo-context pull request #1
Opened 2023-03-28 09:40 UTC by mhenriette

2023-03-29 14:11 UTC, IbrahimBagalwa requested changes
Great work @mhenriette  I left a short comment on what you could improve on.

2023-03-29 14:11 UTC, IbrahimBagalwa commented on src/App.jsx
> +};
It could be fine if could separate your context logic outside your app component and put it in a separate component

2023-03-29 14:11 UTC, IbrahimBagalwa commented on src/components/Form.jsx
> +import TodoContext from "./TodoContext";
Instead of importing in each component this two functionality, it could be fine if you create a hook that you will import only once.

2023-03-29 14:11 UTC, IbrahimBagalwa commented on src/components/Form.jsx
> +    const { tasks, deleteTask, handleClick, getCurrent } = context;
You could destructure directly to the first line instead of doing it twice.

2023-03-29 14:11 UTC, IbrahimBagalwa commented on src/components/Form.jsx
> +                        />
You could destructure here as well

2023-03-29 14:11 UTC, IbrahimBagalwa commented on src/components/Task.jsx
> +const Task = ({ children, onClick, onChange, checked, getCurrentId, id }) => {
Do you really want to pass those props when you are using global state? I think if you want to share the state you could make them a global state

2023-03-30 13:01 UTC, mhenriette commented on src/components/Task.jsx
> +const Task = ({ children, onClick, onChange, checked, getCurrentId, id }) => {
thanks, let me work on them

2023-03-30 14:02 UTC, IbrahimBagalwa reviewed
Well done @mhenriette I left a short comment on what you could improve on.

2023-03-30 14:02 UTC, IbrahimBagalwa commented on src/hook/useTodo.js
> +};
how about if you do:
```javascript
const useTodo = ()=>useContext(TodoContext)
```

2023-03-30 14:02 UTC, IbrahimBagalwa commented on src/components/Form.jsx
> +        })
here you could write less code that could be more readable like:
```javascript
{tasks.length ? tasks.map({value,id,checked})=><Task children={value} key={id} id={id} /> :<h1>Your code here</h1>}
```

2023-03-30 14:02 UTC, IbrahimBagalwa commented on src/components/ToDo.jsx
> +
can you destructure here as well.

2023-03-30 14:32 UTC, IbrahimBagalwa approved these changes
LGTM 👍

2023-05-09 19:35 UTC, merged